import Link from "next/link";

import { JoinGuildForm } from "@/components/GuildForms";
import { createClient } from "@/lib/supabase/server";

interface GuildPreview {
  id: string;
  name: string;
  curator_count: number;
  critic_count: number;
  max_curators: number;
  max_critics: number;
}

/**
 * The invite landing page — what a prospective member sees when the
 * president's link is shared. Works signed-out (guild_preview is a
 * security-definer RPC): the join button routes through sign-in and back.
 */
export default async function JoinPage({
  params,
}: {
  params: Promise<{ code: string }>;
}) {
  const { code } = await params;
  const supabase = await createClient();

  const [{ data: previews }, { data: auth }] = await Promise.all([
    supabase.rpc("guild_preview", { code }),
    supabase.auth.getUser(),
  ]);
  const preview = previews?.[0] as GuildPreview | undefined;
  const user = auth?.user ?? null;

  if (!preview) {
    return (
      <main className="mx-auto max-w-md px-6 py-16">
        <p className="label-eyebrow">Invitation</p>
        <h1 className="mt-3 text-4xl font-medium uppercase leading-none tracking-tight">
          Invalid Invite
        </h1>
        <p className="mt-6 leading-relaxed text-ink-soft">
          This invite link doesn&apos;t match any guild. Codes can be
          regenerated by the guild president — ask them for a fresh link.
        </p>
      </main>
    );
  }

  const curatorSeats = preview.max_curators - preview.curator_count;
  const criticSeats = preview.max_critics - preview.critic_count;

  return (
    <main className="mx-auto max-w-md px-6 py-16">
      <p className="label-eyebrow">You&apos;re invited to</p>
      <h1 className="mt-3 text-4xl font-medium uppercase leading-none tracking-tight">
        {preview.name}
      </h1>
      <p className="mt-4 text-sm text-ink-soft">
        {preview.curator_count} curator
        {preview.curator_count === 1 ? "" : "s"} · {preview.critic_count} critic
        {preview.critic_count === 1 ? "" : "s"} — a festival of cinema,
        programmed and awarded together
      </p>

      <div className="mt-10">
        {criticSeats <= 0 && curatorSeats <= 0 ? (
          <p className="border border-rule bg-paper-raised p-4 text-sm leading-relaxed">
            This guild is full — every curator and critic seat is taken. Ask the
            president to make room, then try the link again.
          </p>
        ) : user ? (
          <>
            <JoinGuildForm code={code} />
            <p className="mt-5 text-xs leading-relaxed text-ink-faint">
              {curatorSeats > 0
                ? `${curatorSeats} curator seat${curatorSeats === 1 ? "" : "s"} left, and room for ${criticSeats} more critic${criticSeats === 1 ? "" : "s"}.`
                : `Curator seats are full, but there is room for ${criticSeats} more critic${criticSeats === 1 ? "" : "s"}.`}
            </p>
          </>
        ) : (
          <div className="grid gap-3">
            <Link
              href={`/signup?next=${encodeURIComponent(`/join/${code}`)}`}
              className="border border-ink px-5 py-2.5 text-center text-sm uppercase tracking-[0.1em] transition-colors hover:bg-ink hover:text-paper"
            >
              Create an Account to Join
            </Link>
            <Link
              href={`/login?next=${encodeURIComponent(`/join/${code}`)}`}
              className="text-center text-sm text-ink-soft underline hover:text-signal"
            >
              Already a member of the site? Sign in
            </Link>
          </div>
        )}
      </div>
    </main>
  );
}
